import type { NextPage } from 'next';
import Head from 'next/head';

import { MainForm } from 'components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Purshace form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainForm />
    </>
  );
};

export default Home;
